---
title: "Polling with uncertainty built in"
output: html_document
---

```{r, echo = F, warning = F, message = F}
library(tidyverse)
library(DescTools)
```


```{r}
polls_pres_primary <- read_csv("../data/polling_538/polls/president_primary_polls.csv")
names(polls_pres_primary)
summary(polls_pres_primary)
```

```{r}
## checking the recorded sample sizes vs. a rough calculation of number of responses for each candidate, given that 538 only provided percentages as a number between 0 - 100, which is hardly specific. I suppose this is most likely due to differing polling sources. Standardizing in this technique allows for similar scale across polls. 

## For now, we will multiply percentages by sample size and round to the nearest digit, to get a rough estimate of the number of respondents who chose that particular candidate. 

## Some candidates have recorded percentages of zero, which could be up a half a percent for each candidate.  

polls_pres_primary %>% 
  mutate(num = round(pct*sample_size/100, 0)) %>%
  group_by(poll_id, sample_size) %>%
  summarise(sample_size_check = sum(num))
```

```{r}
polls_pres_primary <- polls_pres_primary %>%
  mutate(num = round(pct*sample_size/100, 0)) 

polls_pres_primary <- polls_pres_primary %>%
  group_by(poll_id, sample_size) %>%
  mutate(est = MultinomCI(num)[,1], 
         ci_lower = MultinomCI(num)[,2], 
         ci_upper = MultinomCI(num)[,3]) %>%
  ungroup() %>%
  mutate(end_date_as_date = lubridate::mdy(end_date))


```


```{r}

candidates_running <- c("Andrew Yang", "Amy Klobuchar", "Bernard Sanders", 
                        "Beto O'Rourke", "Bill de Blasio", "Cory A. Booker", 
                        "Elizabeth Warren", "Eric Swalwell", "John Hickenlooper", 
                        "John K. Delaney", "Joseph R. Biden Jr.", "Julián Castro",
                        "Kamala D. Harris","Kirsten E. Gillibrand", "Marianne Williamson", 
                        "Michael F. Bennet", "Jay Robert Inslee",
                        "Pete Buttigieg",  "Steve Bullock", "Tim Ryan", "Tulsi Gabbard")

candidates_toptier <- c("Bernard Sanders", "Elizabeth Warren", "Joseph R. Biden Jr.", 
                        "Kamala D. Harris", "Pete Buttigieg", "Beto O'Rourke", 
                        "Cory A. Booker", "Amy Klobuchar")

polls_pres_primary %>%
  filter(candidate_name %in% candidates_toptier) %>%
  filter(lubridate::year(end_date_as_date) > 2018 & lubridate::month(end_date_as_date) > 3) %>%
  group_by(candidate_name) %>%
  filter(max(pct) > 1) %>%
  ungroup() %>%
  group_by(end_date_as_date, candidate_name, population) %>%
  mutate(ci_lower = min(ci_lower), ci_upper = max(ci_upper), est = mean(est)) %>%
  ungroup() %>%
  mutate(fte_grade = factor(fte_grade, levels = c("A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "NA" ), labels = c("A", "A", "A", "B", "B", "B", "C", "C", "C", "NA"))) %>%
  ggplot() + 
  geom_ribbon(aes(x = end_date_as_date, 
                  ymin = ci_lower, ymax = ci_upper, 
                  group = candidate_name, 
                  fill = candidate_name), 
              alpha = 0.5) + 
  geom_line(aes(x = end_date_as_date, 
                y = est, 
                group = candidate_name, 
                color = candidate_name)) + 
  facet_grid(fte_grade~population) + 
  theme_bw()
  
```



